env: centos7java1.8
build:
   bash: mvn clean compile war:war
   artifacts: ./target/petclinic.war
screenshot:
   server: ./mvnw tomcat7:run
   client: firefox localhost:9966/petclinic
sonar:
   bash: mvn sonar:sonar
