env: centos7java1.8
build:
   bash: mvn compile war:war
   artifacts: ./target/petclinic.war
   test:|
      Xvfb :1 -screen 0 1280x960x24 &
      sleep 4
      firefox localhost:9966/petclinic &
      BPID=$!
      sleep 10
      import -window root -crop 1264x948+0+0 -resize 800x600 -quality 95 screenshot.jpg
      kill -9 $BPID
sonar:
   bash: mvn sonar:sonar

